# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "reads_bwamem2_decontamination"

description: Short-reads mapping to a reference genome and remove matching reads
keywords:
  - decontamination
  - short-reads
  - mapping

components:
  - bwamem2/mem
  - samtools/bam2fq

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - reads:
      type: file
      description: |
        A list of input FastQ files of size 1 or 2
        for single-end and paired-end data, respectively
      pattern: "*.{fastq/fq}.gz"
  - meta2:
      type: map
      description: |
        Groovy Map containing reference genome information
        e.g. [ id:'ref_name' ]
  - ref_index:
      type: file
      description: |
        A list of BWA index reference files
      pattern: "*.{amb,ann,bwt,pac,sa}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - decont_reads:
      type: file
      description: |
        A list of decontaminated FastQ files of size 1 or 2
        for single-end and paired-end data, respectively
  - versions:
      type: file
      description: |
        File containing software versions
      Structure: [path(versions.yml)]
      pattern: "versions.yml"

authors:
  - "@Ales-ibt"
maintainers:
  - "@Ales-ibt"
  - "@mberacochea"
