repository_type: pipeline
org_path: ebi-metagenomics
template:
  prefix: ebi-metagenomics
  skip:
    - ci
    - github_badges
lint:
  files_exist:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-miassembler_logo_light.png
    - docs/images/nf-core-miassembler_logo_light.png
    - docs/images/nf-core-miassembler_logo_dark.png
    - docs/output.md
    - docs/usage.md
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
    - .github/workflows/branch.yml
    - .github/workflows/ci.yml
    - .github/workflows/linting_comment.yml
    - .github/workflows/linting.yml
    - conf/test_full.config
    - lib/Utils.groovy
    - lib/WorkflowMain.groovy
    - lib/NfcoreTemplate.groovy
    - lib/WorkflowMiassembler.groovy
    - lib/nfcore_external_java_deps.jar
  files_unchanged:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-miassembler_logo_light.png
    - docs/images/nf-core-miassembler_logo_light.png
    - docs/images/nf-core-miassembler_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/CONTRIBUTING.md
    - LICENSE
    - docs/README.md
    - .gitignore
  multiqc_config:
    - report_comment
  nextflow_config: False
    - params.input
    - params.validationSchemaIgnoreParams
    - params.custom_config_version
    - params.custom_config_base
    - manifest.name
    - manifest.homePage
  readme:
    - nextflow_badge
