name: "BWA2"
description: Map reads to reference genome
keywords:
  - mapping
  - bwa
tools:
  - "bwa2":
      description: "Mapping DNA sequences against a large reference genome"
      tool_dev_url: "https://github.com/bwa-mem2/bwa-mem2"

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - reads:
      type: file
      description: |
        List of input FastQ files of size 1 and 2
        for single-end and paired-end data, respectively.
  - meta2:
      type: map
      description: |
        Groovy Map containing reference genome information
        e.g. [ id:'ref_name' ]
  - ref_index:
      type: file
      description: |
        A list of BWA index reference files

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - bam_file:
      type: file
      description: |
        Sorted alignment in bam format
  - bai_file:
      type: file
      description: |
        Index of sorted bam file
  - versions:
      type: file
      description: |
        File containing software versions

authors:
  - "@EBI-Metagenomics"
maintainers:
  - "@EBI-Metagenomics"
