name: minimap2_align
description: A versatile pairwise aligner for genomic and spliced nucleotide sequences
keywords:
  - align
  - fasta
  - fastq
  - genome
  - paf
  - reference
tools:
  - minimap2:
      description: |
        A versatile pairwise aligner for genomic and spliced nucleotide sequences.
      homepage: https://github.com/lh3/minimap2
      documentation: https://github.com/lh3/minimap2#uguide
      licence: ["MIT"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - reads:
      type: file
      description: |
        List of input FASTA or FASTQ files of size 1 and 2 for single-end
        and paired-end data, respectively.
  - meta2:
      type: map
      description: |
        Groovy Map containing reference information
        e.g. [ id:'test_ref']
  - reference:
      type: file
      description: |
        Reference database in FASTA format.
  - prefix2:
      type: string
      description: |
        Gives a different prefix to output files depending on the reference used
  - fa_fq_format:
      type: string
      description: |
        Matches either "fasta" or "fastq" depending on the input file
  - bam_format:
      type: boolean
      description: Specify that output should be in BAM format
  - bam_index_extension:
      type: string
      description: BAM alignment index extension (e.g. "bai")
  - cigar_paf_format:
      type: boolean
      description: Specify that output CIGAR should be in PAF format
  - cigar_bam:
      type: boolean
      description: |
        Write CIGAR with >65535 ops at the CG tag. This is recommended when
        doing XYZ (https://github.com/lh3/minimap2#working-with-65535-cigar-operations)
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - filtered_output:
      type: file
      description: |
        Sequence file (fasta or fastq) after filtering
  - paf:
      type: file
      description: Alignment in PAF format
      pattern: "*.paf"
  - bam:
      type: file
      description: Alignment in BAM format
      pattern: "*.bam"
  - index:
      type: file
      description: BAM alignment index
      pattern: "*.bam.*"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@heuermh"
  - "@sofstam"
  - "@sateeshperi"
  - "@jfy133"
  - "@fellen31"
maintainers:
  - "@heuermh"
  - "@sofstam"
  - "@sateeshperi"
  - "@jfy133"
  - "@fellen31"
