---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "hifiadapterfilt"
description: "Convert .bam to .fastq and remove reads with remnant PacBio adapter sequences"
keywords:
  - pacbio
  - hifi
  - filter
  - metagenomics
tools:
  - "hifiadapterfilt":
      description: "Convert .bam to .fastq and remove CCS reads with remnant PacBio adapter sequences"
      homepage: "https://bio.tools/hifiadapterfilt"
      documentation: "https://github.com/sheinasim/HiFiAdapterFilt"
      tool_dev_url: "https://github.com/sheinasim/HiFiAdapterFilt"
      doi: "10.1186/s12864-022-08375-1"
      licence: ["GPL-3.0"]
      identifier: biotools:hifiadapterfilt
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1', single_end:false ]`
  - fastq:
      type: file
      description: Fastq pacbio hifi raw reads file
      pattern: "*.{fastq}"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1', single_end:false ]`
  - filt:
      type: file
      description: |
        Fastq reads free of pacbio adapter sequence ready for assembly
      pattern: "*.filt.fastq.gz"
  - blast_search:
      type: file
      description: |
        Output of BLAST search
      pattern: "*.contaminant.blastout"
  - stats:
      type: file
      description: |
        File with simple math on number of reads removed, etc
      pattern: "*.stats"
  - headers:
      type: file
      description: |
        Headers of pacbio adapter contaminated reads to be removed
      pattern: "*.blocklist"
  - versions:
    - "versions.yml":
        type: file
        description: File containing software versions
        pattern: "versions.yml"
authors:
  - "@Ge94"
maintainers:
  - "@Ge94"
