name: nf-test CI
on:
  pull_request:
  release:
    types: [published]
  workflow_dispatch:

env:
  NXF_ANSI_LOG: false

jobs:
  test:
    name: Run pipeline with test data
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Nextflow versions: check pipeline minimum and current latest
        NXF_VER: ["24.04.0"]

    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v4

      - name: Setup Nextflow
        uses: nf-core/setup-nextflow@v2.0.0
        with:
          version: "${{ matrix.NXF_VER }}"

      - name: Install nf-test
        uses: nf-core/setup-nf-test@v1
        with:
          install-pdiff: true

      - name: Run pipeline with test data
        run: |
          nf-test test --tag samplesheet --ci
